// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx37k8hJR_Ql5KY76xDcTTH9zqbw6zcDQ',
    appId: '1:600866466531:web:64baebf675b461475d73d6',
    messagingSenderId: '600866466531',
    projectId: 'garbage-classifier-c80fa',
    authDomain: 'garbage-classifier-c80fa.firebaseapp.com',
    storageBucket: 'garbage-classifier-c80fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAucUEnO9PPPr2re-d6m6BhDtfsZM4peb4',
    appId: '1:600866466531:android:6e4d5dd938bd9a495d73d6',
    messagingSenderId: '600866466531',
    projectId: 'garbage-classifier-c80fa',
    storageBucket: 'garbage-classifier-c80fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwb3mSHbewsN3wESowIzHuKr7T0pFtTmI',
    appId: '1:600866466531:ios:3f83a6979f95d9825d73d6',
    messagingSenderId: '600866466531',
    projectId: 'garbage-classifier-c80fa',
    storageBucket: 'garbage-classifier-c80fa.firebasestorage.app',
    iosBundleId: 'com.example.workshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwb3mSHbewsN3wESowIzHuKr7T0pFtTmI',
    appId: '1:600866466531:ios:3f83a6979f95d9825d73d6',
    messagingSenderId: '600866466531',
    projectId: 'garbage-classifier-c80fa',
    storageBucket: 'garbage-classifier-c80fa.firebasestorage.app',
    iosBundleId: 'com.example.workshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx37k8hJR_Ql5KY76xDcTTH9zqbw6zcDQ',
    appId: '1:600866466531:web:2c58b0582528debd5d73d6',
    messagingSenderId: '600866466531',
    projectId: 'garbage-classifier-c80fa',
    authDomain: 'garbage-classifier-c80fa.firebaseapp.com',
    storageBucket: 'garbage-classifier-c80fa.firebasestorage.app',
  );
}
